### ISSUE TITLE
Compilation Issue with ONL -  Connection Failure

### ISSUE THREAD

**Issue by pnayek8470** [opencomputeproject/OpenNetworkLinux#1016]
Description
When attempting to compile Open Network Linux (ONL), the build process fails due to issues with accessing APT repositories. The system attempts to use the APT proxy at http://127.0.0.1:3142, but the connection fails with the error:
Err http://127.0.0.1:3142 unstable Release.gpg - Connection failed.

This prevents successful installation of necessary dependencies during the build process.

Steps to Reproduce
Clone the ONL repository.
Follow the standard steps to initiate the build process.
Observe the output during the dependency installation phase.

<img width="611" alt="Image" src="https://github.com/user-attachments/assets/64cc5392-d348-4662-b321-f2055a2e4770" />

**Comment by bgurdagargela** [comment]
We have just started experiencing a similar problem during our ONL builds. The error we get is as follows:

W: Failed to fetch http://127.0.0.1:3142/apt.opennetlinux.org/debian/dists/unstable/main/binary-amd64/Packages 500 Connection failure: Network is unreachable

E: Some index files failed to download. They have been ignored, or old ones used instead.
apt update failed. Exit value: 100

**Comment by sonoble** [comment]
Sorry about all that, the domains are fine but were not updated to the new server.  That is all being done now, once you can reach apt.opennetlinux.org again it should start working.  The server it is moved to is ocp.opennetlinux.org.

**Comment by pnayek8470** [comment]
how to update these links could you please tell us

**Comment by pnayek8470** [comment]
also could you help me how to upgrade the GCC 4.7 to GCC 9 inside docker and everytime when I run the docker I need the docker to start with GCC 9 version

**Comment by sonoble** [comment]
Depending on what docker image you are using you can modify the latest
Dockerfile and build a new image or update and save your updated version.

https://github.com/opencomputeproject/OpenNetworkLinux/tree/master/docker/images/builder10/1.2

**Comment by pnayek8470** [comment]
Hi Team,

I attempted to compile ONL from scratch, but I encountered some download errors. I have already updated the links from "apt.opennetlinux.org" to "ocp.opennetlinux.org", but the issue still persists.

 
<img width="965" alt="Image" src="https://github.com/user-attachments/assets/47005358-5d6d-4729-8498-2a4bb66f04d7" />

Could you please check and let me know if there's a proper patch available or any recommended fix for this issue?

Steps Followed:

1: git clone -b f0bcb23 https://github.com/opencomputeproject/OpenNetworkLinux.git
2: apt-cacher-ng
3: source setup.env
4:make amd64

**Comment by pnayek8470** [comment]
Hi team,

we are facing stilll issue with compilation as we have fixed the link issue regarding server migration but still it is not able to locate packages from the repo "http://ocp.opennetlinux.org/debian/dists/unstable/main/binary-amd64/" 

I followed this PR request to make the changes

https://github.com/jonathantsai-qci/OpenNetworkLinux/commit/7182b36153ddd3444ada7001f66325bd0d5dba7e

But packages were not found 

<img width="539" alt="Image" src="https://github.com/user-attachments/assets/b53780ee-573e-4544-9a14-473f302e67f1" />

**Comment by jonathantsai-qci** [comment]
Sirs,

My PR(https://github.com/jonathantsai-qci/OpenNetworkLinux/commit/7182b36153ddd3444ada7001f66325bd0d5dba7e) had error as below. Please Experts help resolve this issue. Thank you so much.

Build steps as follows:
1. git clone https://github.com/opencomputeproject/OpenNetworkLinux.git
2. cd OpenNetworkLinux
3. make docker

![Image](https://github.com/user-attachments/assets/560a1407-81f7-4db4-aafa-e07934c73e20)

**Comment by pnayek8470** [comment]
Hi team,

we are facing stilll issue with compilation as we have fixed the link issue regarding server migration but still it is not able to locate packages from the repo "http://ocp.opennetlinux.org/debian/dists/unstable/main/binary-amd64/"

I followed this PR request to make the changes

https://github.com/jonathantsai-qci/OpenNetworkLinux/commit/7182b36153ddd3444ada7001f66325bd0d5dba7e

But packages were not found


![Image](https://github.com/user-attachments/assets/ce44c5ee-a41d-4ace-90b2-ba001c3cd00e)

**Comment by yogch** [comment]
Is there any solution for this?
We're still experiencing issues and cannot build.

**Comment by sadgnu** [comment]
cannot build, have same issue  as Jonathantsai-qci
E: Failed to fetch http://127.0.0.1:3142/ocp.opennetlinux.org/debian/dists/unstable/main/binary-amd64/Packages.gz  Hash Sum mismatch

**Comment by capveg** [comment]
A bunch of problems with the ONL website have just been fixed - can you please try again and report if it's working now?

**Comment by jhengpinglin-lab** [comment]
> A bunch of problems with the ONL website have just been fixed - can you please try again and report if it's working now?

Hi Capveg,
we still cannot get the **ocp.opennetlinux.org/debian/dists/unstable/main/binary-amd64/Packages**

<img width="1178" height="993" alt="Image" src="https://github.com/user-attachments/assets/9d13d538-0bae-4007-a2c6-386a31827618" />

**Comment by capveg** [comment]
THanks - I think this is a simple fix.  Let me talk to @kevinkifer-ocp and see if we can get https://ocp.opennetlinux.org/debian/dists/unstable/main/binary-amd64/Packages fixed up too.

**Comment by jhengpinglin-lab** [comment]
> THanks - I think this is a simple fix. Let me talk to [@kevinkifer-ocp](https://github.com/kevinkifer-ocp) and see if we can get https://ocp.opennetlinux.org/debian/dists/unstable/main/binary-amd64/Packages fixed up too.


Hi Capveg,

Thanks for your help. the packeages can be downloaded again.

By the way, is the possible we can keep those packages in local build server and compiler the ONL off line?

**Comment by dogukangulyasar** [comment]
Hi @capveg,

After resolving the Packages download failure issue, we are now facing an "Unable to locate package" error for two packages:
- hw-management
- sx-kernel

When I checked the old Packages.gz file, I could clearly see that hw-management was listed, but sx-kernel was not. For example:
```
Package: hw-management
Version: 1.mlnx.2.0.0191
Architecture: amd64
Maintainer: MellanoxBSP <system-sw-low-level@mellanox.com>
Installed-Size: 158
Depends: init-system-helpers (>= 1.18~), libc6 (>= 2.2.5)
Filename: dists/unstable/main/binary-amd64/hw-management_1.mlnx.2.0.0191_amd64.deb
Size: 22930
MD5sum: 8b44dc828295056cc8290da927f6042d
SHA1: cfc1babe653a76b31f6384c0189a6b16f434f219
SHA256: 980aad1745372171fbdd3788f6402a0562d86f91662b2593a9154c9093add2cc
Section: utils
Priority: optional
Homepage: http://www.mellanox.com
Description: Thermal control and chassis management for Mellanox systems
      This package supports Mellanox switches family for chassis
      management and thermal control.
However, when I check the new Packages file, neither hw-management nor sx-kernel are listed.
```

But the new Package file does not includes any of these packages.
Do you think the problem is directly related to this difference, or do you have any suggestions on how we should proceed?

Thanks.

**Comment by rayxhuangEC** [comment]
I build failed for `Hash Sum mismatch` as same with sadgnu.

```
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://127.0.0.1:3142/apt.opennetlinux.org/debian/dists/unstable/main/binary-amd64/Packages.gz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:8920 [weak]
    - SHA512:96ae706e4828c64d68dbe213ce4258db93fa805c48773fc67532f2287b739ce1bb50eb46fb59404aa140d9430e1a7cbdacabfab7056b397b2d5b77ff21f30730
    - SHA256:f9a46f04e19a24c94344297de1d8a0b4e71e872a1d954dd88321a7f87634cd41
    - SHA1:ce6268e0874f74c9b34e8473a2398d0204ac48cb [weak]
    - MD5Sum:852802fe44212f6bdd59a9f4e80cda1f [weak]
   Hashes of received file:
    - SHA512:32fb66016f695f9f35d6b219f4ab4f5e81c33b8a17b61dfb10912d47b53c9e1c5bfa13745fa5d3226a811f0fe2ea67aba6cfd2356d2d0fe073548a0bbe84360e
    - SHA256:1fa835f352b906be654f67c6daa7ad2c6577e78420581dc57b2f3d7ed9703eff
    - SHA1:f1efa08173dab0c25cc6ca232e0a7ee5682ec20e [weak]
    - MD5Sum:e1f590de181c1c915f6ece0fc16ac0a0 [weak]
    - Filesize:8920 [weak]
   Last modification reported: Thu, 21 Apr 2016 17:12:45 +0000
   Release file created at: Tue, 05 Apr 2016 19:39:19 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
apt update failed. Exit value: 100
INFO:onlrfs:[profiler] sudo /usr/sbin/multistrap -d stretch/rootfs-amd64.d -f /tmp/tmppESz0H : 5.32368302345 seconds (0.0887280503909 minutes)
DEBUG:onlrfs:Executing:sudo mount -t devtmpfs dev stretch/rootfs-amd64.d/dev
INFO:onlrfs:[profiler] sudo mount -t devtmpfs dev stretch/rootfs-amd64.d/dev : 0.0216429233551 seconds (0.000360715389252 minutes)
DEBUG:onlrfs:Executing:sudo mount -t proc proc stretch/rootfs-amd64.d/proc
mount: mount point stretch/rootfs-amd64.d/proc does not exist
ERROR:onlrfs:Exception 'Could not mount proc in rfs.' in OnlRfsContext::__enter__
DEBUG:onlrfs:Executing:sudo umount -l stretch/rootfs-amd64.d/dev stretch/rootfs-amd64.d/proc
umount: stretch/rootfs-amd64.d/proc: mountpoint not found
ERROR:onlrfs:Could not unmount dev and proc
/home/rayx/opennetworklinux-myrepo/make/rfs.mk:50: recipe for target 'RFS' failed
``` 


I comment `ONL-Local` in builds/any/rootfs/stretch/standard/standard.yml seems work. 
But then build failed for `E: Unable to locate package hw-management` as same with dogukangulyasar.

```
Note, selecting 'python-scapy' instead of 'scapy'
E: Unable to locate package hw-management
apt download failed. Exit value: 100
INFO:onlrfs:[profiler] sudo /usr/sbin/multistrap -d stretch/rootfs-amd64.d -f /tmp/tmpLIyXoe : 5.99989914894 seconds (0.099998319149 minutes)
ERROR:onlrfs:Multistrap APT failure.
```

Is there any one knows how to fix it?
